use rstest_reuse::template;

#[template]
#[rstest]
#[case::plain("job-1")]
#[case::underscored("job_1")]
#[case::dotted("job.1")]
#[case::digits("2026-10-08")]
#[case::suffixed("job-1.state.json")]
#[case::doubled_suffix("job-1.state.json.state.json")]
#[case::tripled_suffix("job-1.state.json.state.json.state.json")]
#[case::nested("sub/job-1")]
#[case::deep("sub-1/sub-2/sub-3/job-1")]
#[case::uppercase("Job-1")]
#[case::unicode("café-日本語")]
#[case::ideographs("日本語")]
#[case::emoji("job-🚀")]
#[case::space("job 1")]
#[case::hidden(".job-1")]
#[case::trailing_dot("job-1.")]
#[case::trailing_space("job-1 ")]
#[case::double_dot("job..1")]
#[case::only_dots("...")]
#[case::punctuation("job@1~2")]
#[case::single_character("j")]
#[case::uppercase_suffix("job-1.STATE.JSON")]
#[case::only_looks_suffixed("mystate.json")]
#[case::bare_suffix_word("state.json")]
#[case::suffix_only(".state.json")]
#[case::partial_suffix("job-1.state")]
#[case::json_suffix("job-1.json")]
#[case::temporary_suffix("job-1.state.json.tmp")]
#[case::tmp_suffix("job-1.tmp")]
#[case::nested_suffix("sub/job-1.state.json")]
#[case::nested_suffix_only("sub/.state.json")]
#[case::state_shaped_directory("archive.state.json/job-1")]
#[case::hidden_component("sub/.job-1")]
#[case::hidden_directory(".sub/job-1")]
#[case::nested_trailing_dot("sub/job-1.")]
#[case::nested_trailing_space("sub/job-1 ")]
#[case::percent_encoded_traversal("%2e%2e/job-1")]
#[case::two_dot_leader("\u{2025}/job-1")]
#[case::fullwidth_solidus("\u{ff0e}\u{ff0e}\u{ff0f}job-1")]
#[case::device_before_a_letter("console")]
#[case::unnumbered_printer_port("lpt")]
#[case::zero_port("com0")]
#[case::two_digit_port("com10")]
#[case::device_with_a_suffix("con-1")]
#[case::device_inside_a_word("nullable")]
#[case::device_as_a_prefix("auxiliary")]
#[case::hidden_device(".con")]
#[case::device_prefixed_directory("console/job-1")]
#[case::device_with_a_no_break_space("con\u{a0}")]
#[case::arabic("مرحبا")]
#[case::hebrew("שלום")]
#[case::cyrillic("привет")]
#[case::combining_mark("e\u{301}")]
#[case::no_break_space("job\u{a0}1")]
#[case::ideographic_space("job\u{3000}1")]
#[case::yen_sign("job¥1")]
#[case::won_sign("job₩1")]
#[case::fullwidth_reverse_solidus("job\u{ff3c}1")]
#[case::fullwidth_quotation_mark("job\u{ff02}1")]
#[case::title_case_letter("ǅungla")]
#[case::modifier_letter("コーヒー")]
#[case::spacing_mark("किताब")]
#[case::enclosing_mark("job\u{20dd}")]
#[case::letter_number("Ⅻ")]
#[case::other_number("job½²")]
#[case::brackets("job(1)[2]{3}")]
#[case::quotation_marks("«job»“1”")]
#[case::modifier_symbols("job^1`")]
#[case::console_input_without_a_dollar("conin")]
#[case::device_after_a_letter("xcon")]
#[case::zero_printer_port("lpt0")]
#[case::superscript_port_with_a_digit("com¹0")]
fn valid_names(#[case] name: &str) {}

#[template]
#[rstest]
#[case::empty("", NameError::Empty)]
#[case::current_dir(".", NameError::Invalid)]
#[case::only_current_dirs("./.", NameError::Invalid)]
#[case::current_dir_with_a_separator("./", NameError::Invalid)]
#[case::leading_current_dir("./job-1", NameError::Invalid)]
#[case::repeated_current_dir("././job-1", NameError::Invalid)]
#[case::interior_current_dir("sub/./job-1", NameError::Invalid)]
#[case::trailing_current_dir("sub/job-1/.", NameError::Invalid)]
#[case::repeated_separator("sub//job-1", NameError::Invalid)]
#[case::trailing_separator("job-1/", NameError::Invalid)]
#[case::repeated_trailing_separator("job-1//", NameError::Invalid)]
#[case::parent("..", NameError::Escapes)]
#[case::traversal("../../etc/passwd", NameError::Escapes)]
#[case::inner_traversal("foo/../bar", NameError::Escapes)]
#[case::shallow_traversal("../job-1", NameError::Escapes)]
#[case::trailing_parent("sub/..", NameError::Escapes)]
#[case::traversal_past_a_directory("sub/../../job-1", NameError::Escapes)]
#[case::traversal_that_stays_inside("sub/../job-1", NameError::Escapes)]
#[case::traversal_after_a_current_dir("./../job-1", NameError::Escapes)]
#[case::root("/", NameError::Escapes)]
#[case::absolute("/var", NameError::Escapes)]
#[case::absolute_file("/etc/passwd", NameError::Escapes)]
#[case::double_leading_separator("//job-1", NameError::Escapes)]
#[case::only_separators("///", NameError::Escapes)]
#[case::forward_slash_share("//server/share/job-1", NameError::Escapes)]
fn invalid_names(#[case] name: &str, #[case] expected: NameError) {}

#[template]
#[rstest]
#[case::backslash_traversal(r"..\..\etc\passwd")]
#[case::root_relative(r"\job-1")]
#[case::unc_share(r"\\server\share\job-1")]
#[case::verbatim_drive(r"\\?\C:\job-1")]
#[case::drive_absolute(r"C:\job-1")]
#[case::drive_forward_slash("C:/job-1")]
#[case::drive_relative("C:job-1")]
#[case::bare_drive("c:")]
#[case::backslash_parent(r"..\job-1")]
#[case::device_namespace(r"\\.\pipe\job-1")]
#[case::backslash_separated(r"sub\job-1")]
#[case::mixed_separators(r"sub-1\sub-2/job-1")]
#[case::alternate_stream("job:1")]
#[case::nested_alternate_stream("sub/job:1")]
#[case::directory_ending_in_a_dot("sub./job-1")]
#[case::directory_ending_in_dots("sub../job-1")]
#[case::directory_of_only_dots(".../job-1")]
#[case::directory_ending_in_a_space("sub /job-1")]
#[case::nested_directory_ending_in_a_dot("sub-1/sub-2./job-1")]
fn windows_invalid_names(#[case] name: &str) {}

#[template]
#[rstest]
#[case::backslash('\\')]
#[case::colon(':')]
#[case::asterisk('*')]
#[case::question_mark('?')]
#[case::quotation_mark('"')]
#[case::less_than('<')]
#[case::greater_than('>')]
#[case::pipe('|')]
#[case::null('\0')]
#[case::tab('\t')]
#[case::newline('\n')]
#[case::carriage_return('\r')]
#[case::unit_separator('\u{1f}')]
#[case::delete('\u{7f}')]
#[case::next_line('\u{85}')]
#[case::escape('\u{1b}')]
#[case::right_to_left_override('\u{202e}')]
#[case::zero_width_space('\u{200b}')]
#[case::zero_width_joiner('\u{200d}')]
#[case::byte_order_mark('\u{feff}')]
#[case::soft_hyphen('\u{ad}')]
#[case::line_separator('\u{2028}')]
#[case::private_use('\u{e000}')]
#[case::unassigned('\u{378}')]
#[case::noncharacter('\u{ffff}')]
#[case::paragraph_separator('\u{2029}')]
fn unportable_characters(#[case] character: char) {}

#[template]
#[rstest]
#[case::console("con")]
#[case::uppercase("CON")]
#[case::printer("prn")]
#[case::auxiliary("aux")]
#[case::null("nul")]
#[case::mixed_case_with_an_extension("Nul.txt")]
#[case::trailing_space_with_an_extension("nul .txt")]
#[case::double_extension("nul.tar.gz")]
#[case::first_port("com1")]
#[case::ninth_port("COM9")]
#[case::superscript_one_port("com\u{b9}")]
#[case::first_printer_port("lpt1")]
#[case::superscript_three_printer_port("lpt\u{b3}")]
#[case::console_input("conin$")]
#[case::console_output("CONOUT$")]
#[case::device_with_an_extension("con.txt")]
#[case::device_directory("con/job-1")]
#[case::nested_device("sub/aux")]
#[case::nested_device_with_an_extension("sub/com1.log")]
#[case::second_port("COM2")]
#[case::third_port("COM3")]
#[case::fourth_port("COM4")]
#[case::fifth_port("COM5")]
#[case::sixth_port("COM6")]
#[case::seventh_port("COM7")]
#[case::eighth_port("COM8")]
#[case::superscript_two_port("com²")]
#[case::superscript_three_port("COM³")]
#[case::second_printer_port("LPT2")]
#[case::third_printer_port("LPT3")]
#[case::fourth_printer_port("LPT4")]
#[case::fifth_printer_port("LPT5")]
#[case::sixth_printer_port("LPT6")]
#[case::seventh_printer_port("LPT7")]
#[case::eighth_printer_port("LPT8")]
#[case::ninth_printer_port("LPT9")]
#[case::superscript_one_printer_port("lpt¹")]
#[case::superscript_two_printer_port("LPT²")]
#[case::trailing_spaces("con  ")]
#[case::trailing_dot("aux.")]
fn device_names(#[case] name: &str) {}

#[template]
#[rstest]
#[case::file("f".repeat(219))]
#[case::multibyte_file(format!("{}abc", "\u{1f680}".repeat(54)))]
#[case::directory(format!("{}/job-1", "d".repeat(255)))]
#[case::whole_name(format!("{0}/{0}/{0}/{0}/{1}", "d".repeat(100), "f".repeat(108)))]
fn longest_names(#[case] name: String) {}

#[template]
#[rstest]
#[case::file("f".repeat(220))]
#[case::multibyte_file(format!("{}abcd", "\u{1f680}".repeat(54)))]
#[case::directory(format!("{}/job-1", "d".repeat(256)))]
#[case::whole_name(format!("{0}/{0}/{0}/{0}/{1}", "d".repeat(100), "f".repeat(109)))]
fn too_long_names(#[case] name: String) {}
