use rstest_reuse::template;

#[template]
#[rstest]
#[case::plain("job-1")]
#[case::underscored("job_1")]
#[case::dotted("job.1")]
#[case::digits("2026-10-08")]
#[case::suffixed("job-1.state.json")]
#[case::doubled_suffix("job-1.state.json.state.json")]
#[case::tripled_suffix("job-1.state.json.state.json.state.json")]
#[case::nested("sub/job-1")]
#[case::deep("sub-1/sub-2/sub-3/job-1")]
#[case::uppercase("Job-1")]
#[case::unicode("café-日本語")]
#[case::ideographs("日本語")]
#[case::emoji("job-🚀")]
#[case::space("job 1")]
#[case::hidden(".job-1")]
#[case::trailing_dot("job-1.")]
#[case::trailing_space("job-1 ")]
#[case::double_dot("job..1")]
#[case::only_dots("...")]
#[case::punctuation("job@1~2")]
#[case::single_character("j")]
#[case::different_case_suffix("job-1.STATE.JSON")]
#[case::only_looks_suffixed("mystate.json")]
#[case::bare_suffix_word("state.json")]
#[case::suffix_only(".state.json")]
#[case::partial_suffix("job-1.state")]
#[case::json_suffix("job-1.json")]
#[case::temporary_suffix("job-1.state.json.tmp")]
#[case::tmp_suffix("job-1.tmp")]
#[case::nested_suffix("sub/job-1.state.json")]
#[case::suffix_as_the_last_component("sub/.state.json")]
#[case::state_shaped_directory("archive.state.json/job-1")]
#[case::hidden_component("sub/.job-1")]
#[case::hidden_directory(".sub/job-1")]
#[case::nested_trailing_dot("sub/job-1.")]
#[case::nested_trailing_space("sub/job-1 ")]
#[case::percent_encoded_traversal("%2e%2e/job-1")]
#[case::two_dot_leader("\u{2025}/job-1")]
#[case::fullwidth_solidus("\u{ff0e}\u{ff0e}\u{ff0f}job-1")]
#[case::device_prefix("console")]
#[case::unnumbered_port("lpt")]
#[case::zero_port("com0")]
#[case::two_digit_port("com10")]
#[case::device_with_a_suffix("con-1")]
#[case::device_inside_a_word("nullable")]
#[case::device_as_a_prefix("auxiliary")]
#[case::hidden_device(".con")]
#[case::device_inside_a_directory("console/job-1")]
fn valid_names(#[case] name: &str) {}

#[template]
#[rstest]
#[case::empty("", Rule::Empty)]
#[case::current_dir(".", Rule::Invalid)]
#[case::only_current_dirs("./.", Rule::Invalid)]
#[case::current_dir_with_a_separator("./", Rule::Invalid)]
#[case::leading_current_dir("./job-1", Rule::Invalid)]
#[case::repeated_current_dir("././job-1", Rule::Invalid)]
#[case::interior_current_dir("sub/./job-1", Rule::Invalid)]
#[case::trailing_current_dir("sub/job-1/.", Rule::Invalid)]
#[case::repeated_separator("sub//job-1", Rule::Invalid)]
#[case::trailing_separator("job-1/", Rule::Invalid)]
#[case::repeated_trailing_separator("job-1//", Rule::Invalid)]
#[case::parent("..", Rule::Escapes)]
#[case::traversal("../../etc/passwd", Rule::Escapes)]
#[case::inner_traversal("foo/../bar", Rule::Escapes)]
#[case::shallow_traversal("../x", Rule::Escapes)]
#[case::trailing_parent("foo/..", Rule::Escapes)]
#[case::traversal_past_a_directory("sub/../../x", Rule::Escapes)]
#[case::traversal_that_stays_inside("sub/../job-1", Rule::Escapes)]
#[case::traversal_after_a_current_dir("./../x", Rule::Escapes)]
#[case::root("/", Rule::Escapes)]
#[case::absolute("/var", Rule::Escapes)]
#[case::absolute_file("/etc/passwd", Rule::Escapes)]
#[case::double_leading_separator("//x", Rule::Escapes)]
#[case::only_separators("///", Rule::Escapes)]
#[case::forward_slash_share("//server/share/job-1", Rule::Escapes)]
fn invalid_names(#[case] name: &str, #[case] rule: Rule) {}

#[template]
#[rstest]
#[case::backslash_traversal(r"..\..\etc\passwd")]
#[case::root_relative(r"\job-1")]
#[case::unc_share(r"\\server\share\job-1")]
#[case::verbatim_drive(r"\\?\C:\job-1")]
#[case::drive_absolute(r"C:\job-1")]
#[case::drive_forward_slash("C:/job-1")]
#[case::drive_relative("C:job-1")]
#[case::bare_drive("c:")]
#[case::backslash_parent(r"..\x")]
#[case::device_namespace(r"\\.\pipe\job-1")]
#[case::backslash_separated(r"sub\job-1")]
#[case::mixed_separators(r"sub-1\sub-2/job-1")]
#[case::alternate_stream("job:1")]
#[case::nested_alternate_stream("sub/job:1")]
#[case::directory_ending_in_a_dot("sub./job-1")]
#[case::directory_of_dots("sub../job-1")]
#[case::directory_of_only_dots(".../job-1")]
#[case::directory_ending_in_a_space("sub /job-1")]
#[case::deep_directory_ending_in_a_dot("sub-1/sub-2./job-1")]
fn windows_invalid_names(#[case] name: &str) {}

#[template]
#[rstest]
#[case::backslash('\\')]
#[case::colon(':')]
#[case::asterisk('*')]
#[case::question_mark('?')]
#[case::quote('"')]
#[case::less_than('<')]
#[case::greater_than('>')]
#[case::pipe('|')]
#[case::nul('\0')]
#[case::tab('\t')]
#[case::newline('\n')]
#[case::carriage_return('\r')]
#[case::unit_separator('\u{1f}')]
#[case::delete('\u{7f}')]
#[case::next_line('\u{85}')]
fn unportable_characters(#[case] character: char) {}

#[template]
#[rstest]
#[case::console("con")]
#[case::uppercase("CON")]
#[case::printer("prn")]
#[case::auxiliary("aux")]
#[case::null("nul")]
#[case::mixed_case_with_an_extension("Nul.txt")]
#[case::extension_after_a_space("nul .txt")]
#[case::double_extension("nul.tar.gz")]
#[case::first_port("com1")]
#[case::last_port("COM9")]
#[case::superscript_port("com\u{b9}")]
#[case::first_printer_port("lpt1")]
#[case::superscript_printer_port("lpt\u{b3}")]
#[case::console_input("conin$")]
#[case::console_output("CONOUT$")]
#[case::device_with_an_extension("con.txt")]
#[case::device_directory("con/job-1")]
#[case::nested_device("sub/aux")]
#[case::nested_device_with_an_extension("sub/com1.log")]
fn device_names(#[case] name: &str) {}
