import pytest

VALID_STATE_NAMES = [
    pytest.param("job-1", id="plain"),
    pytest.param("job_1", id="underscored"),
    pytest.param("job.1", id="dotted"),
    pytest.param("2026-10-08", id="digits"),
    pytest.param("job-1.state.json", id="suffixed"),
    pytest.param("job-1.state.json.state.json", id="doubled_suffix"),
    pytest.param("job-1.state.json.state.json.state.json", id="tripled_suffix"),
    pytest.param("sub/job-1", id="nested"),
    pytest.param("sub-1/sub-2/sub-3/job-1", id="deep"),
    pytest.param("Job-1", id="uppercase"),
    pytest.param("café-日本語", id="unicode"),
    pytest.param("日本語", id="ideographs"),
    pytest.param("job-🚀", id="emoji"),
    pytest.param("job 1", id="space"),
    pytest.param(".job-1", id="hidden"),
    pytest.param("job-1.", id="trailing_dot"),
    pytest.param("job-1 ", id="trailing_space"),
    pytest.param("job..1", id="double_dot"),
    pytest.param("...", id="only_dots"),
    pytest.param("job@1~2", id="punctuation"),
    pytest.param("j", id="single_character"),
    pytest.param("job-1.STATE.JSON", id="uppercase_suffix"),
    pytest.param("mystate.json", id="only_looks_suffixed"),
    pytest.param("state.json", id="bare_suffix_word"),
    pytest.param(".state.json", id="suffix_only"),
    pytest.param("job-1.state", id="partial_suffix"),
    pytest.param("job-1.json", id="json_suffix"),
    pytest.param("job-1.state.json.tmp", id="temporary_suffix"),
    pytest.param("job-1.tmp", id="tmp_suffix"),
    pytest.param("sub/job-1.state.json", id="nested_suffix"),
    pytest.param("sub/.state.json", id="nested_suffix_only"),
    pytest.param("archive.state.json/job-1", id="state_shaped_directory"),
    pytest.param("sub/.job-1", id="hidden_component"),
    pytest.param(".sub/job-1", id="hidden_directory"),
    pytest.param("sub/job-1.", id="nested_trailing_dot"),
    pytest.param("sub/job-1 ", id="nested_trailing_space"),
    pytest.param("%2e%2e/job-1", id="percent_encoded_traversal"),
    pytest.param("\u2025/job-1", id="two_dot_leader"),
    pytest.param("\uff0e\uff0e\uff0fjob-1", id="fullwidth_solidus"),
    pytest.param("console", id="device_before_a_letter"),
    pytest.param("lpt", id="unnumbered_printer_port"),
    pytest.param("com0", id="zero_port"),
    pytest.param("com10", id="two_digit_port"),
    pytest.param("con-1", id="device_with_a_suffix"),
    pytest.param("nullable", id="device_inside_a_word"),
    pytest.param("auxiliary", id="device_as_a_prefix"),
    pytest.param(".con", id="hidden_device"),
    pytest.param("console/job-1", id="device_prefixed_directory"),
    pytest.param("con\u00a0", id="device_with_a_no_break_space"),
    pytest.param("مرحبا", id="arabic"),
    pytest.param("שלום", id="hebrew"),
    pytest.param("привет", id="cyrillic"),
    pytest.param("e\u0301", id="combining_mark"),
    pytest.param("job\u00a01", id="no_break_space"),
    pytest.param("job\u30001", id="ideographic_space"),
    pytest.param("job¥1", id="yen_sign"),
    pytest.param("job₩1", id="won_sign"),
    pytest.param("job\uff3c1", id="fullwidth_reverse_solidus"),
    pytest.param("job\uff021", id="fullwidth_quotation_mark"),
    pytest.param("ǅungla", id="title_case_letter"),
    pytest.param("コーヒー", id="modifier_letter"),
    pytest.param("किताब", id="spacing_mark"),
    pytest.param("job\u20dd", id="enclosing_mark"),
    pytest.param("Ⅻ", id="letter_number"),
    pytest.param("job½²", id="other_number"),
    pytest.param("job(1)[2]{3}", id="brackets"),
    pytest.param("«job»“1”", id="quotation_marks"),
    pytest.param("job^1`", id="modifier_symbols"),
    pytest.param("conin", id="console_input_without_a_dollar"),
    pytest.param("xcon", id="device_after_a_letter"),
    pytest.param("lpt0", id="zero_printer_port"),
    pytest.param("com¹0", id="superscript_port_with_a_digit"),
]
NON_CANONICAL_STATE_NAMES = [
    pytest.param(".", id="current_dir"),
    pytest.param("./.", id="only_current_dirs"),
    pytest.param("./", id="current_dir_with_a_separator"),
    pytest.param("./job-1", id="leading_current_dir"),
    pytest.param("././job-1", id="repeated_current_dir"),
    pytest.param("sub/./job-1", id="interior_current_dir"),
    pytest.param("sub/job-1/.", id="trailing_current_dir"),
    pytest.param("sub//job-1", id="repeated_separator"),
    pytest.param("job-1/", id="trailing_separator"),
    pytest.param("job-1//", id="repeated_trailing_separator"),
]
ESCAPING_STATE_NAMES = [
    pytest.param("..", id="parent"),
    pytest.param("../../etc/passwd", id="traversal"),
    pytest.param("foo/../bar", id="inner_traversal"),
    pytest.param("../job-1", id="shallow_traversal"),
    pytest.param("sub/..", id="trailing_parent"),
    pytest.param("sub/../../job-1", id="traversal_past_a_directory"),
    pytest.param("sub/../job-1", id="traversal_that_stays_inside"),
    pytest.param("./../job-1", id="traversal_after_a_current_dir"),
    pytest.param("/", id="root"),
    pytest.param("/var", id="absolute"),
    pytest.param("/etc/passwd", id="absolute_file"),
    pytest.param("//job-1", id="double_leading_separator"),
    pytest.param("///", id="only_separators"),
    pytest.param("//server/share/job-1", id="forward_slash_share"),
]
STATE_NAME_ERRORS = {
    "state name must not be empty": [pytest.param("", id="empty")],
    "is not valid": NON_CANONICAL_STATE_NAMES,
    "escapes the state directory": ESCAPING_STATE_NAMES,
}
INVALID_STATE_NAMES = [case for cases in STATE_NAME_ERRORS.values() for case in cases]
INVALID_STATE_NAME_ERRORS = [
    pytest.param(*case.values, error, id=case.id)
    for error, cases in STATE_NAME_ERRORS.items()
    for case in cases
]
WINDOWS_INVALID_STATE_NAMES = [
    pytest.param("..\\..\\etc\\passwd", id="backslash_traversal"),
    pytest.param("\\job-1", id="root_relative"),
    pytest.param("\\\\server\\share\\job-1", id="unc_share"),
    pytest.param("\\\\?\\C:\\job-1", id="verbatim_drive"),
    pytest.param("C:\\job-1", id="drive_absolute"),
    pytest.param("C:/job-1", id="drive_forward_slash"),
    pytest.param("C:job-1", id="drive_relative"),
    pytest.param("c:", id="bare_drive"),
    pytest.param("..\\job-1", id="backslash_parent"),
    pytest.param("\\\\.\\pipe\\job-1", id="device_namespace"),
    pytest.param("sub\\job-1", id="backslash_separated"),
    pytest.param("sub-1\\sub-2/job-1", id="mixed_separators"),
    pytest.param("job:1", id="alternate_stream"),
    pytest.param("sub/job:1", id="nested_alternate_stream"),
    pytest.param("sub./job-1", id="directory_ending_in_a_dot"),
    pytest.param("sub../job-1", id="directory_ending_in_dots"),
    pytest.param(".../job-1", id="directory_of_only_dots"),
    pytest.param("sub /job-1", id="directory_ending_in_a_space"),
    pytest.param("sub-1/sub-2./job-1", id="nested_directory_ending_in_a_dot"),
]
UNPORTABLE_CHARACTERS = [
    pytest.param("\\", id="backslash"),
    pytest.param(":", id="colon"),
    pytest.param("*", id="asterisk"),
    pytest.param("?", id="question_mark"),
    pytest.param('"', id="quotation_mark"),
    pytest.param("<", id="less_than"),
    pytest.param(">", id="greater_than"),
    pytest.param("|", id="pipe"),
    pytest.param("\0", id="null"),
    pytest.param("\t", id="tab"),
    pytest.param("\n", id="newline"),
    pytest.param("\r", id="carriage_return"),
    pytest.param("\x1f", id="unit_separator"),
    pytest.param("\x7f", id="delete"),
    pytest.param("\x85", id="next_line"),
    pytest.param("\x1b", id="escape"),
    pytest.param("\u202e", id="right_to_left_override"),
    pytest.param("\u200b", id="zero_width_space"),
    pytest.param("\u200d", id="zero_width_joiner"),
    pytest.param("\ufeff", id="byte_order_mark"),
    pytest.param("\u00ad", id="soft_hyphen"),
    pytest.param("\u2028", id="line_separator"),
    pytest.param("\ue000", id="private_use"),
    pytest.param("\u0378", id="unassigned"),
    pytest.param("\uffff", id="noncharacter"),
    pytest.param("\u2029", id="paragraph_separator"),
]
DEVICE_STATE_NAMES = [
    pytest.param("con", id="console"),
    pytest.param("CON", id="uppercase"),
    pytest.param("prn", id="printer"),
    pytest.param("aux", id="auxiliary"),
    pytest.param("nul", id="null"),
    pytest.param("Nul.txt", id="mixed_case_with_an_extension"),
    pytest.param("nul .txt", id="trailing_space_with_an_extension"),
    pytest.param("nul.tar.gz", id="double_extension"),
    pytest.param("com1", id="first_port"),
    pytest.param("COM9", id="ninth_port"),
    pytest.param("com\u00b9", id="superscript_one_port"),
    pytest.param("lpt1", id="first_printer_port"),
    pytest.param("lpt\u00b3", id="superscript_three_printer_port"),
    pytest.param("conin$", id="console_input"),
    pytest.param("CONOUT$", id="console_output"),
    pytest.param("con.txt", id="device_with_an_extension"),
    pytest.param("con/job-1", id="device_directory"),
    pytest.param("sub/aux", id="nested_device"),
    pytest.param("sub/com1.log", id="nested_device_with_an_extension"),
    pytest.param("COM2", id="second_port"),
    pytest.param("COM3", id="third_port"),
    pytest.param("COM4", id="fourth_port"),
    pytest.param("COM5", id="fifth_port"),
    pytest.param("COM6", id="sixth_port"),
    pytest.param("COM7", id="seventh_port"),
    pytest.param("COM8", id="eighth_port"),
    pytest.param("com²", id="superscript_two_port"),
    pytest.param("COM³", id="superscript_three_port"),
    pytest.param("LPT2", id="second_printer_port"),
    pytest.param("LPT3", id="third_printer_port"),
    pytest.param("LPT4", id="fourth_printer_port"),
    pytest.param("LPT5", id="fifth_printer_port"),
    pytest.param("LPT6", id="sixth_printer_port"),
    pytest.param("LPT7", id="seventh_printer_port"),
    pytest.param("LPT8", id="eighth_printer_port"),
    pytest.param("LPT9", id="ninth_printer_port"),
    pytest.param("lpt¹", id="superscript_one_printer_port"),
    pytest.param("LPT²", id="superscript_two_printer_port"),
    pytest.param("con  ", id="trailing_spaces"),
    pytest.param("aux.", id="trailing_dot"),
]
LONGEST_STATE_NAMES = [
    pytest.param("f" * 219, id="file"),
    pytest.param("\U0001f680" * 54 + "abc", id="multibyte_file"),
    pytest.param("d" * 255 + "/job-1", id="directory"),
    pytest.param("/".join(["d" * 100] * 4) + "/" + "f" * 108, id="whole_name"),
]
TOO_LONG_STATE_NAMES = [
    pytest.param("f" * 220, id="file"),
    pytest.param("\U0001f680" * 54 + "abcd", id="multibyte_file"),
    pytest.param("d" * 256 + "/job-1", id="directory"),
    pytest.param("/".join(["d" * 100] * 4) + "/" + "f" * 109, id="whole_name"),
]
NON_STATE_FILES = [
    pytest.param("README.md", id="plain"),
    pytest.param("job-1.state.json.bak", id="suffix_shaped"),
    pytest.param("job-1.state", id="partial_suffix"),
    pytest.param("job-1.state.json.tmp", id="temporary_suffix"),
    pytest.param("job-2.STATE.JSON", id="uppercase_suffix"),
]
FOREIGN_STATE_FILES = [
    pytest.param(
        "job-1.state.json.state.json", "job-1.state.json", id="doubled_suffix"
    ),
    pytest.param(
        "sub/job-1.state.json.state.json",
        "sub/job-1.state.json",
        id="nested_doubled_suffix",
    ),
    pytest.param(
        "archive.state.json/job-1.state.json",
        "archive.state.json/job-1",
        id="state_shaped_directory",
    ),
    pytest.param(".job-2.state.json", ".job-2", id="hidden"),
    pytest.param("Job-2.state.json", "Job-2", id="uppercase"),
    pytest.param("café.state.json", "café", id="unicode"),
    pytest.param("job 2.state.json", "job 2", id="space"),
]
UNADDRESSABLE_FILES = [
    pytest.param(".state.json", id="bare_suffix"),
    pytest.param("sub/.state.json", id="nested_bare_suffix"),
    pytest.param("..state.json", id="current_dir_stem"),
    pytest.param("...state.json", id="parent_dir_stem"),
]
UNREPRESENTABLE_FILES = [
    pytest.param("sub\\job-2.state.json", id="backslash"),
    pytest.param("job:2.state.json", id="colon"),
    pytest.param("job*2.state.json", id="asterisk"),
    pytest.param("sub./job-2.state.json", id="directory_ending_in_a_dot"),
    pytest.param("sub /job-2.state.json", id="directory_ending_in_a_space"),
    pytest.param("job\t2.state.json", id="control_character"),
]
