import string

TEST_STATE_NAME = "job-1"
TEST_OTHER_STATE_NAME = "job-2"
TEST_SUB_STATE_NAME = "sub"
TEST_MISSING_STATE_NAME = "job-missing"
TEST_NESTED_STATE_NAME = "sub-1/sub-2/job-1"
TEST_DEEP_STATE_NAME = "sub-1/sub-2/sub-3/sub-4/job-1"
TEST_EVERY_DEPTH = (TEST_STATE_NAME, TEST_NESTED_STATE_NAME, TEST_DEEP_STATE_NAME)
TEST_STATE_FILE_EXTENSION = ".state.json"
TEST_STATE_FILE = f"{TEST_STATE_NAME}{TEST_STATE_FILE_EXTENSION}"
TEST_DEFAULT_DELIMITER = ","
TEST_ALPHABET = string.ascii_lowercase.encode()
TEST_WINDOW = 4096
TEST_LARGE_COPIES = 2560
