import string

TEST_STATE_NAME = "job-1"
TEST_STATE_FILE_EXTENSION = ".state.json"
TEST_STATE_FILE = f"{TEST_STATE_NAME}{TEST_STATE_FILE_EXTENSION}"
TEST_DEFAULT_DELIMITER = ","
TEST_ALPHABET = string.ascii_lowercase.encode()
