"""
A Python package that reads a file along with its read percentage.
"""

from datetime import datetime
from os import PathLike
from pathlib import Path
from typing import final

@final
class ByteIterator(IteratorBase):
    def __iter__(self, /) -> ByteIterator: ...
    def __next__(self, /) -> bytes: ...
    def __repr__(self, /) -> str: ...

@final
class ChunkIterator(IteratorBase):
    def __iter__(self, /) -> ChunkIterator: ...
    def __next__(self, /) -> bytes: ...
    def __repr__(self, /) -> str: ...
    @property
    def chunk_size(self, /) -> int: ...
    @property
    def drop_partial(self, /) -> bool: ...

@final
class Config:
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, *, buffer_capacity: int = ..., state_dir: str |PathLike[str] = ..., auto_save_state: bool = False, auto_save_state_bytes: int = ..., auto_load_state: bool = False, verify_state: bool = ...) -> Config: ...
    def __repr__(self, /) -> str: ...
    @property
    def auto_load_state(self, /) -> bool: ...
    @property
    def auto_save_state(self, /) -> bool: ...
    @property
    def auto_save_state_bytes(self, /) -> int: ...
    @property
    def buffer_capacity(self, /) -> int: ...
    @property
    def state_dir(self, /) -> Path: ...
    @property
    def verify_state(self, /) -> bool: ...

@final
class DelimiterIterator(IteratorBase):
    def __iter__(self, /) -> DelimiterIterator: ...
    def __next__(self, /) -> bytes: ...
    def __repr__(self, /) -> str: ...
    @property
    def delimiter(self, /) -> int: ...
    @property
    def keep_delimiter(self, /) -> bool: ...
    @property
    def skip_empty(self, /) -> bool: ...
    @property
    def skip_remaining(self, /) -> int: ...

@final
class FileMetadata:
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def fingerprint(self, /) -> str: ...
    @property
    def mtime(self, /) -> datetime: ...
    @property
    def path(self, /) -> Path: ...
    @property
    def size(self, /) -> int: ...

class IteratorBase:
    def percent(self, /) -> float: ...
    @property
    def state(self, /) -> State: ...

@final
class IteratorOptions:
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __new__(cls, /, *, start: int = 0, end: int = ..., skip: int = 0, limit: int = ...) -> IteratorOptions: ...
    def __repr__(self, /) -> str: ...
    @property
    def end(self, /) -> int: ...
    @property
    def limit(self, /) -> int: ...
    @property
    def skip(self, /) -> int: ...
    @property
    def start(self, /) -> int: ...

@final
class LineIterator(IteratorBase):
    def __iter__(self, /) -> LineIterator: ...
    def __next__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...
    @property
    def keepends(self, /) -> bool: ...
    @property
    def skip_empty(self, /) -> bool: ...
    @property
    def skip_remaining(self, /) -> int: ...

@final
class PReader:
    def __new__(cls, /, *, config: Config = ...) -> PReader: ...
    def __repr__(self, /) -> str: ...
    def bytes(self, /, file: str |PathLike[str], *, state: State |str |None = ..., options: IteratorOptions = ...) -> ByteIterator: ...
    def chunks(self, /, file: str |PathLike[str], *, state: State |str |None = ..., options: IteratorOptions = ..., chunk_size: int = ..., drop_partial: bool = False) -> ChunkIterator: ...
    @property
    def config(self, /) -> Config: ...
    def delimiter(self, /, file: str |PathLike[str], *, state: State |str |None = ..., options: IteratorOptions = ..., delimiter: str, keep_delimiter: bool = False, align_start: bool = False, skip_empty: bool = False) -> DelimiterIterator: ...
    def lines(self, /, file: str |PathLike[str], *, state: State |str |None = ..., options: IteratorOptions = ..., keepends: bool = False, align_start: bool = False, skip_empty: bool = False) -> LineIterator: ...
    @property
    def states(self, /) -> StateRegistry: ...

@final
class State:
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    def checksum(self, /) -> str: ...
    @property
    def file(self, /) -> FileMetadata: ...
    @property
    def name(self, /) -> str: ...
    def path(self, /) -> Path: ...
    def percent(self, /) -> float: ...
    @property
    def position(self, /) -> int: ...
    def resync(self, /, path: str |PathLike[str]) -> State: ...
    def save(self, /) -> Path: ...
    @property
    def timestamps(self, /) -> Timestamps: ...
    def verify(self, /) -> None: ...

class SaveWarning(UserWarning):
    def __new__(cls, /, *_args) -> SaveWarning: ...

class StateError(Exception):
    def __new__(cls, /, *_args) -> StateError: ...

@final
class StateIterator:
    def __iter__(self, /) -> StateIterator: ...
    def __next__(self, /) -> str: ...
    def __repr__(self, /) -> str: ...

@final
class StateRegistry:
    def __contains__(self, name: str, /) -> bool: ...
    def __delitem__(self, name: str, /) -> None: ...
    def __getitem__(self, name: str, /) -> State: ...
    def __iter__(self, /) -> StateIterator: ...
    def __len__(self, /) -> int: ...
    def __repr__(self, /) -> str: ...
    def all(self, /) -> list[State]: ...
    def clear(self, /) -> None: ...
    def delete(self, /, name: str) -> None: ...
    def exists(self, /, name: str) -> bool: ...
    def find(self, /, name: str) -> State |None: ...
    def load(self, /, name: str) -> State: ...
    def names(self, /) -> StateIterator: ...
    def path(self, /, name: str) -> Path: ...
    def search(self, /, pattern: str) -> StateIterator: ...
    @property
    def state_dir(self, /) -> Path: ...

@final
class Timestamps:
    def __eq__(self, value: object, /) -> bool: ...
    def __ne__(self, value: object, /) -> bool: ...
    def __repr__(self, /) -> str: ...
    @property
    def created_at(self, /) -> datetime: ...
    @property
    def updated_at(self, /) -> datetime: ...
