name: Security

on:
  pull_request:
    branches:
      - main

permissions: {}

env:
  CARGO_TERM_COLOR: "always"

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      discussions: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  python-uv-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Run uv audit
        run: make uv-audit

  rust-cargo-deny:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check
          log-level: error
          arguments: --all-features

  rust-cargo-machete:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: bnjbvr/cargo-machete@v0.9.2

  rust-cargo-udeps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-udeps

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --locked

      - name: Run cargo udeps
        run: make cargo-udeps

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      security-events: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@v0.6.3
