name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

env:
  CARGO_TERM_COLOR: "always"

jobs:
  rust-cargo-test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    env:
      RUSTFLAGS: "-Dwarnings"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --locked

      - name: Run cargo test
        run: make cargo-test

      - name: Run cargo nextest
        run: make cargo-nextest

      - name: Run cargo doc test
        run: make cargo-doc-test

  python-pytest:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.12"
          - "3.13"
          - "3.14"
          - "3.14t"
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - uses: astral-sh/setup-uv@v10.0.1
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --locked

      - name: Run pytest
        run: make pytest
